site_name: Aleksander Chmielewski — Data Engineering Portfolio
site_url: https://a-chmielewski.github.io
repo_url: https://github.com/a-chmielewski/openmeteo-etl

theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy
    - toc.follow
  palette:
    - scheme: default
      primary: blue
      accent: blue

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight

plugins:
  - search
  - mermaid2

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Data Model: data_model.md
  - How to Run: how_to_run.md
  - Data Quality: data_quality.md
  - Dashboard: dashboard.md
  - Credits: credits.md
