name: Docs
on:
  push:
    branches: [ main ]
    paths:
      - 'mkdocs.yml'
      - 'docs/**'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12.3' }
      - run: pip install mkdocs mkdocs-material mkdocs-mermaid2
      - run: mkdocs gh-deploy --force
